### ISSUE TITLE
Blackscreen upon going to site

### ISSUE THREAD

**Issue by thrkc** [pagefaultgames/pokerogue#1190]
Title describes issue, console logs below

TypeError: Cannot read properties of undefined (reading 'starterInfoTextSize')
    at B4.setup (index-db565b5f.js:9625:4457)
    at i3.setup (index-db565b5f.js:9641:1713)
    at I3.launchBattle (index-db565b5f.js:10156:27325)
    at Object.callback (index-db565b5f.js:10156:23495)
    at Object.update (index-db565b5f.js:5876:1966)
    at E.emit (index-db565b5f.js:1:3631)
    at Object.step (index-db565b5f.js:5019:799)
    at Object.update (index-db565b5f.js:5006:3336)
    at Object.step (index-db565b5f.js:466:1778)
    at Object.step (index-db565b5f.js:470:2728)

**Comment by Madmadness65** [comment]
Should be fixed via 70939bf8 now
