### ISSUE TITLE
enable login on self hosting?

### ISSUE THREAD

**Issue by CapnBio** [pagefaultgames/pokerogue#1328]
I had started my own little server among friends, but it seems that it does not have a login screen for a user and password. The reason why I started it was for speed and reliability.  

Currently it is running on "npm run start" but silly me thought it would just start with a login screen but that still has not enabled it. Is there something else that I need to change so it does not bypass the login screen?

**Comment by CapnBio** [comment]
Thank you very much. I'll give it a go

**Comment by CapnBio** [comment]
The good news is that I now get the login screen, but signing up leads me to a loading screen that it does not continue, did I miss something?

I have tried deleting the repository entirely and re-downloading it and following the npm commands, but it does not seem to continue from there.

**Comment by CapnBio** [comment]
I have found the issue


`mylink.com/:1 Access to fetch at 'https://api.pokerogue.net/account/register' from origin 'https://mylink.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.Understand this error
utils.ts:315 
        
        
       POST https://api.pokerogue.net/account/register net::ERR_FAILED 403 (Forbidden)
(anonymous) @ utils.ts:315
apiPost @ utils.ts:304
submitAction @ registration-form-ui-handler.ts:81
(anonymous) @ form-modal-ui-handler.ts:94
emit @ phaser.js?v=bf07fc1c:113
processDownEvents @ phaser.js?v=bf07fc1c:58549
update @ phaser.js?v=bf07fc1c:58340
updateInputPlugins @ phaser.js?v=bf07fc1c:57660
onMouseDown @ phaser.js?v=bf07fc1c:57798
onMouseDown @ phaser.js?v=bf07fc1c:65134
Show 6 more frames
Show lessUnderstand this error
main.ts:25 TypeError: Failed to fetch
    at utils.ts:315:5
    at new Promise (<anonymous>)
    at Module.apiPost (utils.ts:304:10)
    at RegistrationFormUiHandler.submitAction (registration-form-ui-handler.ts:81:15)
    at NineSlice2.<anonymous> (form-modal-ui-handler.ts:94:18)
    at NineSlice2.emit (phaser.js?v=bf07fc1c:113:45)
    at InputPlugin2.processDownEvents (phaser.js?v=bf07fc1c:58549:34)
    at InputPlugin2.update (phaser.js?v=bf07fc1c:58340:41)
    at InputManager2.updateInputPlugins (phaser.js?v=bf07fc1c:57660:55)
    at InputManager2.onMouseDown (phaser.js?v=bf07fc1c:57798:26)
(anonymous) @ main.ts:25Understand this error
utils.ts:315 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at utils.ts:315:5
    at new Promise (<anonymous>)
    at Module.apiPost (utils.ts:304:10)
    at RegistrationFormUiHandler.submitAction (registration-form-ui-handler.ts:81:15)
    at NineSlice2.<anonymous> (form-modal-ui-handler.ts:94:18)
    at NineSlice2.emit (phaser.js?v=bf07fc1c:113:45)
    at InputPlugin2.processDownEvents (phaser.js?v=bf07fc1c:58549:34)
    at InputPlugin2.update (phaser.js?v=bf07fc1c:58340:41)
    at InputManager2.updateInputPlugins (phaser.js?v=bf07fc1c:57660:55)
    at InputManager2.onMouseDown (phaser.js?v=bf07fc1c:57798:26)`

Where would I be able to change this portion?

**Comment by CapnBio** [comment]
Nevermind, I found it over in utils.ts but seems like I am not able to get it to work nicely, am I missing something here? When I first load I get 

`main.ts:103 
        
        
       GET https://pr.neatin3d.com/manifest.json 404 (Not Found)`

Then when trying to sign up I get this twice

```
https://mylink.com/account/register 404 (Not Found)
```

**Comment by torranx** [comment]
Probably because you dont have the server running, only the frontend app (this repo)

**Comment by CapnBio** [comment]
Ah that would make lots of sense now

**Comment by CapnBio** [comment]
Thank you for guiding me into the right direction, I will post my results shortly.

**Comment by CapnBio** [comment]
After installing a few required things, looks like I have been able to successfully get it to run, thank you for your guidance!
