### ISSUE TITLE
[BUG] Defeating No Ice Eiscue Freezes Game

### ISSUE THREAD

**Issue by gibsramen** [pagefaultgames/pokerogue#1896]
**Describe the bug**

After beating a No Ice Eiscue, the game freezes without progressing. Game becomes unresponsive to inputs.

**To Reproduce**

1. Encounter Eiscue with Ice Face
2. Defeat Eiscue

**Expected behavior**

Game progresses as normal to EXP gain & item selection.

**Screenshots / Videos**

![image](https://github.com/pagefaultgames/pokerogue/assets/4030868/0f8c7176-07d5-450f-951f-0847fa4b1682)

**Device**

Google Chrome 125.0.6422.142 - PC

**Additional context**

Opened the console and I think this is a result of not finding an audio file.

```
Failed to load resource: the server responded with a status of 404 ()
index-a0846907.js:15685 Error: Audio key "875-no-ice" missing from cache
    at new WebAudioSound (index-a0846907.js:5264:189)
    at d.add (index-a0846907.js:5269:1298)
    at d.play (index-a0846907.js:5129:1109)
    at N6.playSound (index-a0846907.js:15553:26956)
    at J2.faintCry (index-a0846907.js:15002:27563)
    at eV.doFaint (index-a0846907.js:15014:15061)
    at eV.start (index-a0846907.js:15014:13235)
    at N6.shiftPhase (index-a0846907.js:15553:29329)
    at rC.end (index-a0846907.js:14860:186980)
    at rC.end (index-a0846907.js:15014:11098)
window.onerror @ index-a0846907.js:15685
```

Potentially related to fixing #1456 in #1755. I've gotten around this by just capturing it or running away.

**Comment by Tempo-anon** [comment]
An audio file got renamed. Clear your cache (ctrl f5) and refresh. You should be good to go.
