### ISSUE TITLE
[Bug] docker web error

### ISSUE THREAD

**Issue by a877429929** [pagefaultgames/pokerogue#3181]
### Describe the bug

node:internal/fs/watchers:247
    const error = new UVException({
                  ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/app/audio/se/battle_anims/PRSFX- Toxic Thread2.wav'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42512:17)
    at setFsWatchListener (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42559:15)
    at NodeFsHandler._watchWithNodeFs (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42714:14)
    at NodeFsHandler._handleFile (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:42778:23)
    at NodeFsHandler._addToNodeFs (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:43020:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:44213:10)
    at NodeFsHandler._addToNodeFs (file:///usr/local/lib/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:43028:18) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/app/audio/se/battle_anims/PRSFX- Toxic Thread2.wav',
  filename: '/app/audio/se/battle_anims/PRSFX- Toxic Thread2.wav'
}

Node.js v20.13.1

  VITE v5.3.5  ready in 205 ms

### User data export file

![image](https://github.com/user-attachments/assets/be365e33-56f6-4dec-95b5-ef80a66d809e)

### Expected behavior

no

### Screenshots / Videos

no

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Chrome

**Comment by Mewtwo2387** [comment]
Seems like an issue on your machine, try

```
echo fs.inotify.max_user_watches= 131070 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

https://stackoverflow.com/questions/53930305/nodemon-error-system-limit-for-number-of-file-watchers-reached

**Comment by a877429929** [comment]
> Seems like an issue on your machine, try
> 
> ```
> echo fs.inotify.max_user_watches= 131070 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
> ```
> 
> https://stackoverflow.com/questions/53930305/nodemon-error-system-limit-for-number-of-file-watchers-reached

Thanks, I'll try it tonight

**Comment by flx-sta** [comment]
I'll close this as there might be a solution for it.
Feel free to reopen it if the error persists.
