### ISSUE TITLE
Crash involving form changes and swapping egg moves

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#582]
See [this thread](https://discord.com/channels/1125469663833370665/1234889622014922865) for more details but very commonly reported bug with especially Rotom.

Seems to be failing in the [switchMoveHandler](https://github.com/pagefaultgames/pokerogue/blob/3a7a48fe833f9ab1a10339f3fdd4b10b190cdae3/src/ui/starter-select-ui-handler.ts#L1061) of starter-select-ui-handler

```
index-4c078232.js:7415 Uncaught TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at kY.switchMoveHandler (index-4c078232.js:7415:8767)
    at Object.handler (index-4c078232.js:7415:3362)
    at $Y.processInput (index-4c078232.js:7412:1594)
    at Rb.processInput (index-4c078232.js:7431:2929)
    at Pb.checkInput (index-4c078232.js:7946:34693)
    at Pb.update (index-4c078232.js:7946:14821)
    at Object.step (index-4c078232.js:5019:835)
    at Object.update (index-4c078232.js:5006:3336)
    at Object.step (index-4c078232.js:466:1778)
    at Object.step (index-4c078232.js:470:2728)
  ```

**Comment by Tempo-anon** [comment]
Has been fixed
