### ISSUE TITLE
All Pokemon become invisible when capturing then switching with your only pokemon that was not fainted.

### ISSUE THREAD

**Issue by vividiumhd** [pagefaultgames/pokerogue#762]
Was against castform Boss, with my Patrat who was the only one alive. I captured the castform and switch it for my patrat and now all Pokemon are invisible in future challenges.
![image](https://github.com/pagefaultgames/pokerogue/assets/169567606/945e4e01-6d2c-4025-adc3-a09eab584366)

**Comment by vividiumhd** [comment]
Note that I was healed just after this occured since it was on wave 30.

**Comment by vividiumhd** [comment]
Reloading fixed the issue.

**Comment by Snailman11** [comment]
https://discord.com/channels/1125469663833370665/1125894949020381285/1276416529629712438
This is still in the game as of August

**Comment by ysh4296** [comment]
@Snailman11 
Hello, I have checked the issues, Discord, etc.
Unfortunately, my PR(#2371)  does not resolve this issue.
it solves the game freezing issue that can occur when after the lead Pokémon is released 
by fixing UI cursor during the release action.

**Comment by flx-sta** [comment]
<sub>Uploading the discord videos here so they don't get lost when they get automatically deleted by discord servers</sub>

https://github.com/user-attachments/assets/dadf9fd8-9042-4e54-85db-b0982e64d2e3

https://github.com/user-attachments/assets/68cc33e3-dfe4-49af-a83a-079d2df71e14

**Comment by flx-sta** [comment]
[762-testing-session.txt](https://github.com/user-attachments/files/16874301/762-testing-session.txt)

**Comment by flx-sta** [comment]
I found the cause in the code
[pokemon.ts#L4416-L4432](https://github.com/pagefaultgames/pokerogue/blob/fde32cea6c9376a64f6d8dcb4e77cef9b4a0a265/src/field/pokemon.ts#L4416-L4432)

```ts
  addToParty(pokeballType: PokeballType) {
    const party = this.scene.getParty();
    let ret: PlayerPokemon | null = null;

    if (party.length < 6) {
      this.pokeball = pokeballType;
      this.metLevel = this.level;
      this.metBiome = this.scene.arena.biomeType;
      this.metSpecies = this.species.speciesId;
      const newPokemon = this.scene.addPlayerPokemon(this.species, this.level, this.abilityIndex, this.formIndex, this.gender, this.shiny, this.variant, this.ivs, this.nature, this);
      party.push(newPokemon); // <--- If you were to use `.unshift()` here it doesn't cause the bug.
      ret = newPokemon;
      this.scene.triggerPokemonFormChange(newPokemon, SpeciesFormChangeActiveTrigger, true);
    }

    return ret;
  }
  ```

**Comment by flx-sta** [comment]
Still seems too occur after n%10 waves 

see
https://discord.com/channels/1125469663833370665/1284581658649169950

**Comment by flx-sta** [comment]
```
Error: Supplied items must be elements of the same array
    at Object.MoveBelow (/pokerogue/node_modules/phaser/dist/phaser.js:242354:15)
    at Container2.moveBelow (/pokerogue/node_modules/phaser/dist/phaser.js:48330:20)
    at Tween2.onComplete (/pokerogue/src/phases/summon-phase.ts:144:34)
    at Tween2.dispatchEvent (/pokerogue/node_modules/phaser/dist/phaser.js:239603:30)
    at Tween2.onCompleteHandler (/pokerogue/node_modules/phaser/dist/phaser.js:237521:14)
    at Tween2.onCompleteHandler (/pokerogue/node_modules/phaser/dist/phaser.js:239230:47)
    at Tween2.nextState (/pokerogue/node_modules/phaser/dist/phaser.js:239210:18)
    at Tween2.update (/pokerogue/node_modules/phaser/dist/phaser.js:239522:18)
    at TweenManager2.step (/pokerogue/node_modules/phaser/dist/phaser.js:234764:23)
    at TweenManager2.update (http://localhost:8000/node_modules/.vite/deps/phaser.js?v=668d5b6d:132294:28) {stack: 'Error: Supplied items must be elements of the…es/.vite/deps/phaser.js?v=668d5b6d:132294:28)', message: 'Supplied items must be elements of the same array'}
```
